"use client";
/* eslint-disable @next/next/no-img-element -- QR codes are generated data URLs and should not be optimized. */

import { useEffect, useState } from "react";
import { Copy, ShieldCheck, ShieldOff, Smartphone } from "lucide-react";
import { apiDelete, apiGet, apiPost, type SessionResponse } from "@/lib/client-api";
import { PasswordField } from "@/components/auth/password-field";

type Device = { id: string; label: string | null; lastUsedAt: string; expiresAt: string };

export function SecuritySettings() {
  const [enabled, setEnabled] = useState(false); const [devices, setDevices] = useState<Device[]>([]);
  const [password, setPassword] = useState(""); const [code, setCode] = useState(""); const [qr, setQr] = useState<string | null>(null); const [manualKey, setManualKey] = useState(""); const [recoveryCodes, setRecoveryCodes] = useState<string[]>([]); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { void refresh(); }, []);
  async function refresh() { const [session, trusted] = await Promise.all([apiGet<SessionResponse>("/api/session"), apiGet<{ devices: Device[] }>("/api/auth/trusted-devices")]); setEnabled(Boolean(session.user?.twoFactorEnabled)); setDevices(trusted.devices); }
  async function startSetup() { setBusy(true); setError(null); try { const data = await apiPost<{ qrCode: string; manualKey: string }>("/api/auth/2fa/setup", { password }); setQr(data.qrCode); setManualKey(data.manualKey); setPassword(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Setup failed"); } finally { setBusy(false); } }
  async function enable() { setBusy(true); setError(null); try { const data = await apiPost<{ recoveryCodes: string[] }>("/api/auth/2fa/enable", { code }); setRecoveryCodes(data.recoveryCodes); setEnabled(true); setQr(null); setCode(""); setMessage("Two-factor authentication is on."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Code was not accepted"); } finally { setBusy(false); } }
  async function disable() { setBusy(true); setError(null); try { await apiPost("/api/auth/2fa/disable", { code }); setEnabled(false); setCode(""); setMessage("Two-factor authentication is off."); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not disable 2FA"); } finally { setBusy(false); } }
  async function revokeDevices() { await apiDelete("/api/auth/trusted-devices"); setDevices([]); setMessage("Trusted devices revoked."); }
  async function copyCodes() { await navigator.clipboard.writeText(recoveryCodes.join("\n")); setMessage("Recovery codes copied."); }
  const field = "h-11 w-full rounded-lg border border-rim bg-panel2 px-3 text-sm text-frost placeholder:text-slate-600 focus:border-neon/60 focus:outline-none";
  return <section className="mx-auto mt-5 max-w-2xl border-y border-rim py-5" aria-labelledby="security-heading"><div className="flex items-start justify-between gap-4"><div><h2 id="security-heading" className="flex items-center gap-2 text-lg font-black text-frost"><ShieldCheck className="h-5 w-5 text-neon" />Account security</h2><p className="mt-1 text-sm font-normal text-slate-400">Protect password and social sign-ins with an authenticator app.</p></div><span className={`text-xs font-bold ${enabled ? "text-neon" : "text-slate-500"}`}>{enabled ? "2FA ON" : "2FA OFF"}</span></div>
    {!enabled && !qr && <div className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto]"><PasswordField className={field} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Current password (not needed for social-only accounts)" autoComplete="current-password" /><button type="button" disabled={busy} onClick={startSetup} className="h-11 rounded-lg bg-neon px-4 text-sm font-black text-surface disabled:opacity-60">Set up authenticator</button></div>}
    {qr && <div className="mt-5 grid gap-5 sm:grid-cols-[240px_1fr]"><img src={qr} alt="Authenticator setup QR code" className="h-60 w-60 rounded-lg bg-white" /><div><p className="text-sm font-bold text-frost">Scan this code</p><p className="mt-1 text-xs font-normal text-slate-400">Use Google Authenticator, Microsoft Authenticator, 1Password, or another TOTP app.</p><p className="mt-3 break-all rounded bg-panel2 p-2 font-mono text-xs text-slate-300">{manualKey}</p><input className={`${field} mt-3 text-center font-mono tracking-widest`} value={code} onChange={(e) => setCode(e.target.value)} placeholder="000000" autoComplete="one-time-code" /><button type="button" onClick={enable} disabled={busy || code.length !== 6} className="mt-3 h-10 w-full rounded-lg bg-neon text-sm font-black text-surface disabled:opacity-50">Verify and enable</button></div></div>}
    {recoveryCodes.length > 0 && <div className="mt-5 rounded-lg border border-amber/30 bg-amber/10 p-4"><p className="font-bold text-amber">Save these recovery codes now</p><p className="mt-1 text-xs text-slate-300">Each code works once. Store them somewhere outside FantasyX.</p><div className="mt-3 grid grid-cols-2 gap-1 font-mono text-sm text-frost">{recoveryCodes.map((item) => <span key={item}>{item}</span>)}</div><button type="button" onClick={copyCodes} className="mt-3 inline-flex items-center gap-2 text-xs font-bold text-amber"><Copy className="h-3.5 w-3.5" />Copy codes</button></div>}
    {enabled && <div className="mt-5"><label htmlFor="disable-code" className="text-xs font-semibold text-slate-300">Authenticator or recovery code</label><div className="mt-1.5 flex gap-2"><input id="disable-code" className={`${field} font-mono`} value={code} onChange={(e) => setCode(e.target.value)} placeholder="Required to turn off 2FA" /><button type="button" disabled={busy} onClick={disable} className="inline-flex h-11 items-center gap-2 rounded-lg border border-crimson/30 px-4 text-sm font-bold text-crimson"><ShieldOff className="h-4 w-4" />Turn off</button></div></div>}
    <div className="mt-6 flex items-center justify-between border-t border-rim pt-4"><div><p className="flex items-center gap-2 text-sm font-bold text-frost"><Smartphone className="h-4 w-4" />Trusted devices</p><p className="mt-1 text-xs text-slate-500">{devices.length} device{devices.length === 1 ? "" : "s"} can skip 2FA for 30 days.</p></div><button type="button" disabled={!devices.length} onClick={revokeDevices} className="text-xs font-bold text-slate-300 hover:text-frost disabled:opacity-40">Revoke all</button></div>
    {error && <p role="alert" className="mt-4 text-sm font-semibold text-crimson">{error}</p>}{message && <p role="status" className="mt-4 text-sm font-semibold text-neon">{message}</p>}
  </section>;
}
