import type { INflDataProvider } from "./provider";
import type { NflTeam, NflPlayerRecord, NflGameRecord, NflWeekRecord, NflSlateRecord } from "./types";

const DEMO_SEASON = 2026;
const DEMO_WEEK   = 1;

const DEMO_TEAMS: NflTeam[] = [
  { abbreviation: "KC",  city: "Kansas City",   name: "Chiefs",     conference: "AFC", division: "West"  },
  { abbreviation: "LAC", city: "Los Angeles",   name: "Chargers",   conference: "AFC", division: "West"  },
  { abbreviation: "BUF", city: "Buffalo",       name: "Bills",      conference: "AFC", division: "East"  },
  { abbreviation: "NYJ", city: "New York",      name: "Jets",       conference: "AFC", division: "East"  },
  { abbreviation: "BAL", city: "Baltimore",     name: "Ravens",     conference: "AFC", division: "North" },
  { abbreviation: "CLE", city: "Cleveland",     name: "Browns",     conference: "AFC", division: "North" },
  { abbreviation: "CIN", city: "Cincinnati",    name: "Bengals",    conference: "AFC", division: "North" },
  { abbreviation: "PIT", city: "Pittsburgh",    name: "Steelers",   conference: "AFC", division: "North" },
  { abbreviation: "PHI", city: "Philadelphia",  name: "Eagles",     conference: "NFC", division: "East"  },
  { abbreviation: "DAL", city: "Dallas",        name: "Cowboys",    conference: "NFC", division: "East"  },
  { abbreviation: "ATL", city: "Atlanta",       name: "Falcons",    conference: "NFC", division: "South" },
  { abbreviation: "CAR", city: "Carolina",      name: "Panthers",   conference: "NFC", division: "South" },
  { abbreviation: "SF",  city: "San Francisco", name: "49ers",      conference: "NFC", division: "West"  },
  { abbreviation: "SEA", city: "Seattle",       name: "Seahawks",   conference: "NFC", division: "West"  },
  { abbreviation: "MIN", city: "Minnesota",     name: "Vikings",    conference: "NFC", division: "North" },
  { abbreviation: "CHI", city: "Chicago",       name: "Bears",      conference: "NFC", division: "North" },
  { abbreviation: "DET", city: "Detroit",       name: "Lions",      conference: "NFC", division: "North" },
  { abbreviation: "GB",  city: "Green Bay",     name: "Packers",    conference: "NFC", division: "North" },
  { abbreviation: "ARI", city: "Arizona",       name: "Cardinals",  conference: "NFC", division: "West"  },
  { abbreviation: "LV",  city: "Las Vegas",     name: "Raiders",    conference: "AFC", division: "West"  },
  { abbreviation: "MIA", city: "Miami",         name: "Dolphins",   conference: "AFC", division: "East"  },
  { abbreviation: "NE",  city: "New England",   name: "Patriots",   conference: "AFC", division: "East"  },
  { abbreviation: "WAS", city: "Washington",    name: "Commanders", conference: "NFC", division: "East"  },
  { abbreviation: "NYG", city: "New York",      name: "Giants",     conference: "NFC", division: "East"  },
  { abbreviation: "NO",  city: "New Orleans",   name: "Saints",     conference: "NFC", division: "South" },
  { abbreviation: "TB",  city: "Tampa Bay",     name: "Buccaneers", conference: "NFC", division: "South" },
  { abbreviation: "HOU", city: "Houston",       name: "Texans",     conference: "AFC", division: "South" },
  { abbreviation: "JAX", city: "Jacksonville",  name: "Jaguars",    conference: "AFC", division: "South" },
  { abbreviation: "IND", city: "Indianapolis",  name: "Colts",      conference: "AFC", division: "South" },
  { abbreviation: "TEN", city: "Tennessee",     name: "Titans",     conference: "AFC", division: "South" },
  { abbreviation: "LAR", city: "Los Angeles",   name: "Rams",       conference: "NFC", division: "West"  },
  { abbreviation: "DEN", city: "Denver",        name: "Broncos",    conference: "AFC", division: "West"  },
];

const DEMO_GAMES: NflGameRecord[] = [
  { externalId: "demo_game_kc_lac",  homeTeam: "LAC", awayTeam: "KC",  kickoffTime: "2026-09-10T20:20:00-04:00" },
  { externalId: "demo_game_buf_nyj", homeTeam: "BUF", awayTeam: "NYJ", kickoffTime: "2026-09-13T13:00:00-04:00" },
  { externalId: "demo_game_bal_cle", homeTeam: "BAL", awayTeam: "CLE", kickoffTime: "2026-09-13T13:00:00-04:00" },
  { externalId: "demo_game_phi_dal", homeTeam: "PHI", awayTeam: "DAL", kickoffTime: "2026-09-13T16:25:00-04:00" },
  { externalId: "demo_game_atl_car", homeTeam: "ATL", awayTeam: "CAR", kickoffTime: "2026-09-13T13:00:00-04:00" },
  { externalId: "demo_game_sf_sea",  homeTeam: "SF",  awayTeam: "SEA", kickoffTime: "2026-09-13T16:25:00-04:00" },
  { externalId: "demo_game_cin_pit", homeTeam: "CIN", awayTeam: "PIT", kickoffTime: "2026-09-13T13:00:00-04:00" },
  { externalId: "demo_game_min_chi", homeTeam: "MIN", awayTeam: "CHI", kickoffTime: "2026-09-13T13:00:00-04:00" },
  { externalId: "demo_game_det_gb",  homeTeam: "DET", awayTeam: "GB",  kickoffTime: "2026-09-14T20:15:00-04:00" },
  { externalId: "demo_game_ari_lv",  homeTeam: "ARI", awayTeam: "LV",  kickoffTime: "2026-09-13T16:05:00-04:00" },
  { externalId: "demo_game_mia_ne",  homeTeam: "MIA", awayTeam: "NE",  kickoffTime: "2026-09-13T13:00:00-04:00" },
  { externalId: "demo_game_was_nyg", homeTeam: "WAS", awayTeam: "NYG", kickoffTime: "2026-09-13T13:00:00-04:00" },
  { externalId: "demo_game_no_tb",   homeTeam: "NO",  awayTeam: "TB",  kickoffTime: "2026-09-13T13:00:00-04:00" },
  { externalId: "demo_game_hou_jax", homeTeam: "HOU", awayTeam: "JAX", kickoffTime: "2026-09-13T13:00:00-04:00" },
  { externalId: "demo_game_ind_ten", homeTeam: "IND", awayTeam: "TEN", kickoffTime: "2026-09-13T16:05:00-04:00" },
  { externalId: "demo_game_lar_den", homeTeam: "LAR", awayTeam: "DEN", kickoffTime: "2026-09-13T16:25:00-04:00" },
];

const DEMO_PLAYERS: NflPlayerRecord[] = [
  // ── QBs ──────────────────────────────────────────────────────────────────
  { externalId: "demo_josh_allen",          name: "Josh Allen",          teamAbbreviation: "BUF", position: "QB", status: "ACTIVE", projection: 27.4 },
  { externalId: "demo_lamar_jackson",       name: "Lamar Jackson",       teamAbbreviation: "BAL", position: "QB", status: "ACTIVE", projection: 26.1 },
  { externalId: "demo_jalen_hurts",         name: "Jalen Hurts",         teamAbbreviation: "PHI", position: "QB", status: "ACTIVE", projection: 24.8 },
  { externalId: "demo_patrick_mahomes",     name: "Patrick Mahomes",     teamAbbreviation: "KC",  position: "QB", status: "ACTIVE", projection: 24.2 },
  { externalId: "demo_joe_burrow",          name: "Joe Burrow",          teamAbbreviation: "CIN", position: "QB", status: "ACTIVE", projection: 23.5 },
  { externalId: "demo_cj_stroud",           name: "C.J. Stroud",         teamAbbreviation: "HOU", position: "QB", status: "ACTIVE", projection: 22.6 },
  { externalId: "demo_anthony_richardson",  name: "Anthony Richardson",  teamAbbreviation: "IND", position: "QB", status: "ACTIVE", projection: 21.8 },
  { externalId: "demo_dak_prescott",        name: "Dak Prescott",        teamAbbreviation: "DAL", position: "QB", status: "ACTIVE", projection: 21.4 },
  { externalId: "demo_justin_herbert",      name: "Justin Herbert",      teamAbbreviation: "LAC", position: "QB", status: "ACTIVE", projection: 21.0 },
  { externalId: "demo_jordan_love",         name: "Jordan Love",         teamAbbreviation: "GB",  position: "QB", status: "ACTIVE", projection: 20.6 },
  { externalId: "demo_brock_purdy",         name: "Brock Purdy",         teamAbbreviation: "SF",  position: "QB", status: "ACTIVE", projection: 20.2 },
  { externalId: "demo_kyler_murray",        name: "Kyler Murray",        teamAbbreviation: "ARI", position: "QB", status: "ACTIVE", projection: 19.8 },
  { externalId: "demo_tua_tagovailoa",      name: "Tua Tagovailoa",      teamAbbreviation: "MIA", position: "QB", status: "ACTIVE", projection: 19.4 },
  { externalId: "demo_caleb_williams",      name: "Caleb Williams",      teamAbbreviation: "CHI", position: "QB", status: "ACTIVE", projection: 19.0 },
  { externalId: "demo_jayden_daniels",      name: "Jayden Daniels",      teamAbbreviation: "WAS", position: "QB", status: "ACTIVE", projection: 18.8 },
  { externalId: "demo_trevor_lawrence",     name: "Trevor Lawrence",     teamAbbreviation: "JAX", position: "QB", status: "ACTIVE", projection: 18.4 },
  { externalId: "demo_jared_goff",          name: "Jared Goff",          teamAbbreviation: "DET", position: "QB", status: "ACTIVE", projection: 18.0 },
  { externalId: "demo_matthew_stafford",    name: "Matthew Stafford",    teamAbbreviation: "LAR", position: "QB", status: "ACTIVE", projection: 17.6 },
  { externalId: "demo_baker_mayfield",      name: "Baker Mayfield",      teamAbbreviation: "TB",  position: "QB", status: "ACTIVE", projection: 17.2 },
  { externalId: "demo_bo_nix",              name: "Bo Nix",              teamAbbreviation: "DEN", position: "QB", status: "ACTIVE", projection: 16.8 },

  // ── RBs ──────────────────────────────────────────────────────────────────
  { externalId: "demo_christian_mccaffrey", name: "Christian McCaffrey", teamAbbreviation: "SF",  position: "RB", status: "ACTIVE", projection: 22.4 },
  { externalId: "demo_bijan_robinson",      name: "Bijan Robinson",      teamAbbreviation: "ATL", position: "RB", status: "ACTIVE", projection: 19.8 },
  { externalId: "demo_breece_hall",         name: "Breece Hall",         teamAbbreviation: "NYJ", position: "RB", status: "ACTIVE", projection: 19.2 },
  { externalId: "demo_jahmyr_gibbs",        name: "Jahmyr Gibbs",        teamAbbreviation: "DET", position: "RB", status: "ACTIVE", projection: 18.8 },
  { externalId: "demo_saquon_barkley",      name: "Saquon Barkley",      teamAbbreviation: "PHI", position: "RB", status: "ACTIVE", projection: 18.4 },
  { externalId: "demo_jonathan_taylor",     name: "Jonathan Taylor",     teamAbbreviation: "IND", position: "RB", status: "ACTIVE", projection: 17.8 },
  { externalId: "demo_derrick_henry",       name: "Derrick Henry",       teamAbbreviation: "KC",  position: "RB", status: "ACTIVE", projection: 17.4 },
  { externalId: "demo_josh_jacobs",         name: "Josh Jacobs",         teamAbbreviation: "GB",  position: "RB", status: "ACTIVE", projection: 17.0 },
  { externalId: "demo_kyren_williams",      name: "Kyren Williams",      teamAbbreviation: "LAR", position: "RB", status: "ACTIVE", projection: 16.8 },
  { externalId: "demo_devon_achane",        name: "De'Von Achane",       teamAbbreviation: "MIA", position: "RB", status: "ACTIVE", projection: 16.6 },
  { externalId: "demo_travis_etienne",      name: "Travis Etienne",      teamAbbreviation: "JAX", position: "RB", status: "ACTIVE", projection: 16.2 },
  { externalId: "demo_james_cook",          name: "James Cook",          teamAbbreviation: "BUF", position: "RB", status: "ACTIVE", projection: 16.0 },
  { externalId: "demo_kenneth_walker",      name: "Kenneth Walker",      teamAbbreviation: "SEA", position: "RB", status: "ACTIVE", projection: 15.6 },
  { externalId: "demo_joe_mixon",           name: "Joe Mixon",           teamAbbreviation: "HOU", position: "RB", status: "ACTIVE", projection: 15.4 },
  { externalId: "demo_rachaad_white",       name: "Rachaad White",       teamAbbreviation: "TB",  position: "RB", status: "ACTIVE", projection: 15.0 },
  { externalId: "demo_isiah_pacheco",       name: "Isiah Pacheco",       teamAbbreviation: "KC",  position: "RB", status: "ACTIVE", projection: 14.8 },
  { externalId: "demo_alvin_kamara",        name: "Alvin Kamara",        teamAbbreviation: "NO",  position: "RB", status: "ACTIVE", projection: 14.4 },
  { externalId: "demo_david_montgomery",    name: "David Montgomery",    teamAbbreviation: "DET", position: "RB", status: "ACTIVE", projection: 13.8 },
  { externalId: "demo_aaron_jones",         name: "Aaron Jones",         teamAbbreviation: "MIN", position: "RB", status: "ACTIVE", projection: 13.4 },
  { externalId: "demo_najee_harris",        name: "Najee Harris",        teamAbbreviation: "PIT", position: "RB", status: "ACTIVE", projection: 13.0 },
  { externalId: "demo_tony_pollard",        name: "Tony Pollard",        teamAbbreviation: "TEN", position: "RB", status: "ACTIVE", projection: 12.6 },
  { externalId: "demo_brian_robinson",      name: "Brian Robinson",      teamAbbreviation: "WAS", position: "RB", status: "ACTIVE", projection: 12.4 },
  { externalId: "demo_rhamondre_stevenson", name: "Rhamondre Stevenson", teamAbbreviation: "NE",  position: "RB", status: "ACTIVE", projection: 12.0 },
  { externalId: "demo_zamir_white",         name: "Zamir White",         teamAbbreviation: "LV",  position: "RB", status: "ACTIVE", projection: 11.8 },
  { externalId: "demo_dandre_swift",        name: "D'Andre Swift",       teamAbbreviation: "CHI", position: "RB", status: "ACTIVE", projection: 11.6 },
  { externalId: "demo_javonte_williams",    name: "Javonte Williams",    teamAbbreviation: "DEN", position: "RB", status: "ACTIVE", projection: 11.4 },
  { externalId: "demo_chase_brown",         name: "Chase Brown",         teamAbbreviation: "CIN", position: "RB", status: "ACTIVE", projection: 11.0 },
  { externalId: "demo_blake_corum",         name: "Blake Corum",         teamAbbreviation: "LAR", position: "RB", status: "ACTIVE", projection: 10.8 },
  { externalId: "demo_tyjae_spears",        name: "Tyjae Spears",        teamAbbreviation: "TEN", position: "RB", status: "ACTIVE", projection: 10.6 },
  { externalId: "demo_jaylen_warren",       name: "Jaylen Warren",       teamAbbreviation: "PIT", position: "RB", status: "ACTIVE", projection: 10.2 },

  // ── WRs ──────────────────────────────────────────────────────────────────
  { externalId: "demo_justin_jefferson",    name: "Justin Jefferson",    teamAbbreviation: "MIN", position: "WR", status: "ACTIVE", projection: 22.8 },
  { externalId: "demo_jamarr_chase",        name: "Ja'Marr Chase",       teamAbbreviation: "CIN", position: "WR", status: "ACTIVE", projection: 21.6 },
  { externalId: "demo_cee_dee_lamb",        name: "CeeDee Lamb",         teamAbbreviation: "DAL", position: "WR", status: "ACTIVE", projection: 20.8 },
  { externalId: "demo_amon_ra_st_brown",    name: "Amon-Ra St. Brown",   teamAbbreviation: "DET", position: "WR", status: "ACTIVE", projection: 19.6 },
  { externalId: "demo_tyreek_hill",         name: "Tyreek Hill",         teamAbbreviation: "MIA", position: "WR", status: "ACTIVE", projection: 19.2 },
  { externalId: "demo_aj_brown",            name: "A.J. Brown",          teamAbbreviation: "PHI", position: "WR", status: "ACTIVE", projection: 18.8 },
  { externalId: "demo_puka_nacua",          name: "Puka Nacua",          teamAbbreviation: "LAR", position: "WR", status: "ACTIVE", projection: 18.4 },
  { externalId: "demo_garrett_wilson",      name: "Garrett Wilson",      teamAbbreviation: "NYJ", position: "WR", status: "ACTIVE", projection: 18.0 },
  { externalId: "demo_marvin_harrison_jr",  name: "Marvin Harrison Jr.", teamAbbreviation: "ARI", position: "WR", status: "ACTIVE", projection: 17.6 },
  { externalId: "demo_drake_london",        name: "Drake London",        teamAbbreviation: "ATL", position: "WR", status: "ACTIVE", projection: 17.2 },
  { externalId: "demo_chris_olave",         name: "Chris Olave",         teamAbbreviation: "NO",  position: "WR", status: "ACTIVE", projection: 16.8 },
  { externalId: "demo_mike_evans",          name: "Mike Evans",          teamAbbreviation: "TB",  position: "WR", status: "ACTIVE", projection: 16.4 },
  { externalId: "demo_deebo_samuel",        name: "Deebo Samuel",        teamAbbreviation: "SF",  position: "WR", status: "ACTIVE", projection: 16.0 },
  { externalId: "demo_brandon_aiyuk",       name: "Brandon Aiyuk",       teamAbbreviation: "SF",  position: "WR", status: "ACTIVE", projection: 15.8 },
  { externalId: "demo_nico_collins",        name: "Nico Collins",        teamAbbreviation: "HOU", position: "WR", status: "ACTIVE", projection: 15.6 },
  { externalId: "demo_stefon_diggs",        name: "Stefon Diggs",        teamAbbreviation: "NE",  position: "WR", status: "ACTIVE", projection: 15.2 },
  { externalId: "demo_davante_adams",       name: "Davante Adams",       teamAbbreviation: "LV",  position: "WR", status: "ACTIVE", projection: 14.8 },
  { externalId: "demo_dk_metcalf",          name: "DK Metcalf",          teamAbbreviation: "SEA", position: "WR", status: "ACTIVE", projection: 14.6 },
  { externalId: "demo_jaylen_waddle",       name: "Jaylen Waddle",       teamAbbreviation: "MIA", position: "WR", status: "ACTIVE", projection: 14.4 },
  { externalId: "demo_devonta_smith",       name: "DeVonta Smith",       teamAbbreviation: "PHI", position: "WR", status: "ACTIVE", projection: 14.0 },
  { externalId: "demo_tee_higgins",         name: "Tee Higgins",         teamAbbreviation: "CIN", position: "WR", status: "ACTIVE", projection: 13.8 },
  { externalId: "demo_dj_moore",            name: "DJ Moore",            teamAbbreviation: "CHI", position: "WR", status: "ACTIVE", projection: 13.6 },
  { externalId: "demo_keenan_allen",        name: "Keenan Allen",        teamAbbreviation: "CHI", position: "WR", status: "ACTIVE", projection: 13.4 },
  { externalId: "demo_michael_pittman",     name: "Michael Pittman",     teamAbbreviation: "IND", position: "WR", status: "ACTIVE", projection: 13.2 },
  { externalId: "demo_cooper_kupp",         name: "Cooper Kupp",         teamAbbreviation: "LAR", position: "WR", status: "ACTIVE", projection: 13.0 },
  { externalId: "demo_malik_nabers",        name: "Malik Nabers",        teamAbbreviation: "NYG", position: "WR", status: "ACTIVE", projection: 12.8 },
  { externalId: "demo_rome_odunze",         name: "Rome Odunze",         teamAbbreviation: "CHI", position: "WR", status: "ACTIVE", projection: 12.6 },
  { externalId: "demo_tank_dell",           name: "Tank Dell",           teamAbbreviation: "HOU", position: "WR", status: "ACTIVE", projection: 12.4 },
  { externalId: "demo_zay_flowers",         name: "Zay Flowers",         teamAbbreviation: "BAL", position: "WR", status: "ACTIVE", projection: 12.0 },
  { externalId: "demo_george_pickens",      name: "George Pickens",      teamAbbreviation: "PIT", position: "WR", status: "ACTIVE", projection: 11.8 },
  { externalId: "demo_christian_kirk",      name: "Christian Kirk",      teamAbbreviation: "JAX", position: "WR", status: "ACTIVE", projection: 11.6 },
  { externalId: "demo_terry_mclaurin",      name: "Terry McLaurin",      teamAbbreviation: "WAS", position: "WR", status: "ACTIVE", projection: 11.4 },
  { externalId: "demo_amari_cooper",        name: "Amari Cooper",        teamAbbreviation: "CLE", position: "WR", status: "ACTIVE", projection: 11.2 },
  { externalId: "demo_calvin_ridley",       name: "Calvin Ridley",       teamAbbreviation: "TEN", position: "WR", status: "ACTIVE", projection: 11.0 },
  { externalId: "demo_courtland_sutton",    name: "Courtland Sutton",    teamAbbreviation: "DEN", position: "WR", status: "ACTIVE", projection: 10.8 },
  { externalId: "demo_jordan_addison",      name: "Jordan Addison",      teamAbbreviation: "MIN", position: "WR", status: "ACTIVE", projection: 10.6 },
  { externalId: "demo_chris_godwin",        name: "Chris Godwin",        teamAbbreviation: "TB",  position: "WR", status: "ACTIVE", projection: 10.4 },
  { externalId: "demo_rashee_rice",         name: "Rashee Rice",         teamAbbreviation: "KC",  position: "WR", status: "ACTIVE", projection: 10.2 },
  { externalId: "demo_xavier_worthy",       name: "Xavier Worthy",       teamAbbreviation: "KC",  position: "WR", status: "ACTIVE", projection: 10.0 },
  { externalId: "demo_jaxon_smith_njigba",  name: "Jaxon Smith-Njigba",  teamAbbreviation: "SEA", position: "WR", status: "ACTIVE", projection: 9.8  },

  // ── TEs ──────────────────────────────────────────────────────────────────
  { externalId: "demo_travis_kelce",        name: "Travis Kelce",        teamAbbreviation: "KC",  position: "TE", status: "ACTIVE", projection: 15.2 },
  { externalId: "demo_sam_laporta",         name: "Sam LaPorta",         teamAbbreviation: "DET", position: "TE", status: "ACTIVE", projection: 13.6 },
  { externalId: "demo_mark_andrews",        name: "Mark Andrews",        teamAbbreviation: "BAL", position: "TE", status: "ACTIVE", projection: 13.4 },
  { externalId: "demo_trey_mcbride",        name: "Trey McBride",        teamAbbreviation: "ARI", position: "TE", status: "ACTIVE", projection: 13.2 },
  { externalId: "demo_george_kittle",       name: "George Kittle",       teamAbbreviation: "SF",  position: "TE", status: "ACTIVE", projection: 12.8 },
  { externalId: "demo_dalton_kincaid",      name: "Dalton Kincaid",      teamAbbreviation: "BUF", position: "TE", status: "ACTIVE", projection: 12.0 },
  { externalId: "demo_evan_engram",         name: "Evan Engram",         teamAbbreviation: "JAX", position: "TE", status: "ACTIVE", projection: 11.6 },
  { externalId: "demo_kyle_pitts",          name: "Kyle Pitts",          teamAbbreviation: "ATL", position: "TE", status: "ACTIVE", projection: 11.4 },
  { externalId: "demo_jake_ferguson",       name: "Jake Ferguson",       teamAbbreviation: "DAL", position: "TE", status: "ACTIVE", projection: 11.0 },
  { externalId: "demo_brock_bowers",        name: "Brock Bowers",        teamAbbreviation: "LV",  position: "TE", status: "ACTIVE", projection: 10.8 },
  { externalId: "demo_dallas_goedert",      name: "Dallas Goedert",      teamAbbreviation: "PHI", position: "TE", status: "ACTIVE", projection: 10.6 },
  { externalId: "demo_david_njoku",         name: "David Njoku",         teamAbbreviation: "CLE", position: "TE", status: "ACTIVE", projection: 10.2 },
  { externalId: "demo_cole_kmet",           name: "Cole Kmet",           teamAbbreviation: "CHI", position: "TE", status: "ACTIVE", projection: 9.8  },
  { externalId: "demo_pat_freiermuth",      name: "Pat Freiermuth",      teamAbbreviation: "PIT", position: "TE", status: "ACTIVE", projection: 9.6  },
  { externalId: "demo_tj_hockenson",        name: "T.J. Hockenson",      teamAbbreviation: "MIN", position: "TE", status: "ACTIVE", projection: 9.4  },
];

// Maps externalId → game externalId for slate
const PLAYER_GAME_MAP: Record<string, string> = {
  // QBs
  demo_josh_allen:          "demo_game_buf_nyj",
  demo_lamar_jackson:       "demo_game_bal_cle",
  demo_jalen_hurts:         "demo_game_phi_dal",
  demo_patrick_mahomes:     "demo_game_kc_lac",
  demo_joe_burrow:          "demo_game_cin_pit",
  demo_cj_stroud:           "demo_game_hou_jax",
  demo_anthony_richardson:  "demo_game_ind_ten",
  demo_dak_prescott:        "demo_game_phi_dal",
  demo_justin_herbert:      "demo_game_kc_lac",
  demo_jordan_love:         "demo_game_det_gb",
  demo_brock_purdy:         "demo_game_sf_sea",
  demo_kyler_murray:        "demo_game_ari_lv",
  demo_tua_tagovailoa:      "demo_game_mia_ne",
  demo_caleb_williams:      "demo_game_min_chi",
  demo_jayden_daniels:      "demo_game_was_nyg",
  demo_trevor_lawrence:     "demo_game_hou_jax",
  demo_jared_goff:          "demo_game_det_gb",
  demo_matthew_stafford:    "demo_game_lar_den",
  demo_baker_mayfield:      "demo_game_no_tb",
  demo_bo_nix:              "demo_game_lar_den",
  // RBs
  demo_christian_mccaffrey: "demo_game_sf_sea",
  demo_bijan_robinson:      "demo_game_atl_car",
  demo_breece_hall:         "demo_game_buf_nyj",
  demo_jahmyr_gibbs:        "demo_game_det_gb",
  demo_saquon_barkley:      "demo_game_phi_dal",
  demo_jonathan_taylor:     "demo_game_ind_ten",
  demo_derrick_henry:       "demo_game_kc_lac",
  demo_josh_jacobs:         "demo_game_det_gb",
  demo_kyren_williams:      "demo_game_lar_den",
  demo_devon_achane:        "demo_game_mia_ne",
  demo_travis_etienne:      "demo_game_hou_jax",
  demo_james_cook:          "demo_game_buf_nyj",
  demo_kenneth_walker:      "demo_game_sf_sea",
  demo_joe_mixon:           "demo_game_hou_jax",
  demo_rachaad_white:       "demo_game_no_tb",
  demo_isiah_pacheco:       "demo_game_kc_lac",
  demo_alvin_kamara:        "demo_game_no_tb",
  demo_david_montgomery:    "demo_game_det_gb",
  demo_aaron_jones:         "demo_game_min_chi",
  demo_najee_harris:        "demo_game_cin_pit",
  demo_tony_pollard:        "demo_game_ind_ten",
  demo_brian_robinson:      "demo_game_was_nyg",
  demo_rhamondre_stevenson: "demo_game_mia_ne",
  demo_zamir_white:         "demo_game_ari_lv",
  demo_dandre_swift:        "demo_game_min_chi",
  demo_javonte_williams:    "demo_game_lar_den",
  demo_chase_brown:         "demo_game_cin_pit",
  demo_blake_corum:         "demo_game_lar_den",
  demo_tyjae_spears:        "demo_game_ind_ten",
  demo_jaylen_warren:       "demo_game_cin_pit",
  // WRs
  demo_justin_jefferson:    "demo_game_min_chi",
  demo_jamarr_chase:        "demo_game_cin_pit",
  demo_cee_dee_lamb:        "demo_game_phi_dal",
  demo_amon_ra_st_brown:    "demo_game_det_gb",
  demo_tyreek_hill:         "demo_game_mia_ne",
  demo_aj_brown:            "demo_game_phi_dal",
  demo_puka_nacua:          "demo_game_lar_den",
  demo_garrett_wilson:      "demo_game_buf_nyj",
  demo_marvin_harrison_jr:  "demo_game_ari_lv",
  demo_drake_london:        "demo_game_atl_car",
  demo_chris_olave:         "demo_game_no_tb",
  demo_mike_evans:          "demo_game_no_tb",
  demo_deebo_samuel:        "demo_game_sf_sea",
  demo_brandon_aiyuk:       "demo_game_sf_sea",
  demo_nico_collins:        "demo_game_hou_jax",
  demo_stefon_diggs:        "demo_game_mia_ne",
  demo_davante_adams:       "demo_game_ari_lv",
  demo_dk_metcalf:          "demo_game_sf_sea",
  demo_jaylen_waddle:       "demo_game_mia_ne",
  demo_devonta_smith:       "demo_game_phi_dal",
  demo_tee_higgins:         "demo_game_cin_pit",
  demo_dj_moore:            "demo_game_min_chi",
  demo_keenan_allen:        "demo_game_min_chi",
  demo_michael_pittman:     "demo_game_ind_ten",
  demo_cooper_kupp:         "demo_game_lar_den",
  demo_malik_nabers:        "demo_game_was_nyg",
  demo_rome_odunze:         "demo_game_min_chi",
  demo_tank_dell:           "demo_game_hou_jax",
  demo_zay_flowers:         "demo_game_bal_cle",
  demo_george_pickens:      "demo_game_cin_pit",
  demo_christian_kirk:      "demo_game_hou_jax",
  demo_terry_mclaurin:      "demo_game_was_nyg",
  demo_amari_cooper:        "demo_game_bal_cle",
  demo_calvin_ridley:       "demo_game_ind_ten",
  demo_courtland_sutton:    "demo_game_lar_den",
  demo_jordan_addison:      "demo_game_min_chi",
  demo_chris_godwin:        "demo_game_no_tb",
  demo_rashee_rice:         "demo_game_kc_lac",
  demo_xavier_worthy:       "demo_game_kc_lac",
  demo_jaxon_smith_njigba:  "demo_game_sf_sea",
  // TEs
  demo_travis_kelce:        "demo_game_kc_lac",
  demo_sam_laporta:         "demo_game_det_gb",
  demo_mark_andrews:        "demo_game_bal_cle",
  demo_trey_mcbride:        "demo_game_ari_lv",
  demo_george_kittle:       "demo_game_sf_sea",
  demo_dalton_kincaid:      "demo_game_buf_nyj",
  demo_evan_engram:         "demo_game_hou_jax",
  demo_kyle_pitts:          "demo_game_atl_car",
  demo_jake_ferguson:       "demo_game_phi_dal",
  demo_brock_bowers:        "demo_game_ari_lv",
  demo_dallas_goedert:      "demo_game_phi_dal",
  demo_david_njoku:         "demo_game_bal_cle",
  demo_cole_kmet:           "demo_game_min_chi",
  demo_pat_freiermuth:      "demo_game_cin_pit",
  demo_tj_hockenson:        "demo_game_min_chi",
};

const DEMO_SLATE: NflSlateRecord = {
  season: DEMO_SEASON,
  week: DEMO_WEEK,
  players: DEMO_PLAYERS.map((p) => ({
    playerExternalId: p.externalId,
    gameExternalId:   PLAYER_GAME_MAP[p.externalId] ?? "demo_game_kc_lac",
    projection:       p.projection ?? 10,
  })),
};

export class DemoNflDataProvider implements INflDataProvider {
  readonly name: string = "demo";

  async getTeams(): Promise<NflTeam[]> {
    return DEMO_TEAMS;
  }

  async getPlayers(): Promise<NflPlayerRecord[]> {
    return DEMO_PLAYERS;
  }

  async getGames(season: number, week: number): Promise<NflGameRecord[]> {
    if (season === DEMO_SEASON && week === DEMO_WEEK) return DEMO_GAMES;
    return [];
  }

  async getWeeks(season: number): Promise<NflWeekRecord[]> {
    if (season !== DEMO_SEASON) return [];
    return [{
      season: DEMO_SEASON,
      week:   DEMO_WEEK,
      startsAt: "2026-09-08T08:00:00-04:00",
      endsAt:   "2026-09-15T23:59:59-04:00",
    }];
  }

  async getSlate(season: number, week: number): Promise<NflSlateRecord> {
    if (season === DEMO_SEASON && week === DEMO_WEEK) return DEMO_SLATE;
    return { season, week, players: [] };
  }
}
